package org.sapia.corus.client.services.event;

import java.util.Date;

import org.sapia.corus.client.common.json.JsonStreamable;
import org.sapia.ubik.rmi.interceptor.Event;

/**
 * Interface common to all events generated by Corus.
 * 
 * @author yduchesne
 *
 */
public interface CorusEvent extends Event, EventLogCapable, JsonStreamable {

  /**
   * @return the {@link Date} corresponding to the time at which this instance
   * was created.
   */
  public Date getTime();
  
  /**
   * @return this instance's level.
   */
  public EventLevel getLevel();
}
