package org.sapia.corus.docker;

import java.io.InputStream;
import java.util.List;
import java.util.Set;

import org.sapia.corus.client.common.ArgMatcher;
import org.sapia.corus.client.common.log.LogCallback;
import org.sapia.corus.client.services.deployer.dist.StarterResult;
import org.sapia.corus.client.services.deployer.dist.docker.DockerStarter;
import org.sapia.corus.client.services.deployer.dist.docker.DockerStarter.DockerStarterAttachment;
import org.sapia.corus.client.services.docker.DockerContainer;
import org.sapia.corus.client.services.docker.DockerImage;
import org.sapia.corus.processor.hook.ProcessContext;

/**
 * Abstracts Docker client implementations.
 * 
 * @author yduchesne
 *
 */
public interface DockerClientFacade {

  /**
   * @param imageName the name of the Docker image to pull.
   * @param callback the {@link LogCallback} to log to.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public void pullImage(String imageName, LogCallback callback) throws DockerFacadeException;

  /**
   * @param imageName the name of the Docker image to remove.
   * @param callback the {@link LogCallback} to log to.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public void removeImage(String imageName, LogCallback callback) throws DockerFacadeException;

  /**
   * @param imageName the name of the Docker image to load.
   * @param imagePayload the {@link InputStream} corresponding to the image tarball.
   * @param callback the {@link LogCallback} to log to.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public void loadImage(String imageName, InputStream imagePayload, LogCallback callback) throws DockerFacadeException;
  
  /**
   * @param imageName the name of the Docker image to obtain.
   * @param callback the {@link LogCallback} to log to.
   * @return the {@link InputStream} corresponding to the given docker image's tarball.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public InputStream saveImage(String imageName, LogCallback callback) throws DockerFacadeException;

  /**
   * @param context the current {@link ProcessContext}, holding data about the process for which a container should be started.
   * @param starterResult the {@link StarterResult}, holding the results of the {@link DockerStarter} invocation.
   * @param attachment the {@link DockerStarterAttachment}, holding Docker-specific state as set by the {@link DockerStarter}.
   * @param callback the {@link LogCallback} to log to.
   * @return the container ID that was generated by docker.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public String startContainer(ProcessContext context, StarterResult starterResult, DockerStarterAttachment attachment, LogCallback callback) throws DockerFacadeException;
  
  /**
   * @param imageName the name of the image for which to start a new container.
   * @param callback the {@link LogCallback} to write trace logs to.
   * @return the ID of the container that was started.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public String startContainer(String imageName, LogCallback callback) throws DockerFacadeException;
  
  /**
   * @param containerId the ID of the Docker container to stop.
   * @param timeoutMillis the timeout to observe (in millis) while waiting for container shutdown.
   * @param callback the {@link LogCallback} to log to.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public void stopContainer(String containerId, int timeoutMillis, LogCallback callback) throws DockerFacadeException;

  /**
   * @param containerId the ID of the Docker container to remove.
   * @param timeoutMillis the timeout to observe (in millis) while waiting for container shutdown.
   * @param callback the {@link LogCallback} to log to.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public void removeContainer(String containerId, LogCallback callback) throws DockerFacadeException;
  
  /**
   * @param imageName the name of a Docker image.
   * @return <code>true</code> if the Docker daemon has an image corresponding to the given name.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public boolean containsImage(String imageName) throws DockerFacadeException;
  
  /**
   * @param imageNames a {@link Set} of image names whose existence should be checked.
   * @return the {@link Set} of image names whose corresponding images could NOT be found.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public Set<String> checkContainsImages(Set<String> imageNames) throws DockerFacadeException;
  
  /**
   * @param tagMatcher the {@link ArgMatcher} to use for matching against Docker image tags.
   * @return the {@link List} of {@link DockerImage}s matching the given criterion.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public List<DockerImage> listImages(ArgMatcher tagMatcher) throws DockerFacadeException;
  
  /**
   * @param nameMatcher the {@link ArgMatcher} to use for matching against Docker container names/image names.
   * @return the {@link List} of {@link DockerContainer}s matching the given criterion.
   * @throws DockerFacadeException if an error occurs while performing this operation.
   */
  public List<DockerContainer> listContainers(ArgMatcher nameMatcher) throws DockerFacadeException;
  
}
